import { Platform, StyleSheet } from 'react-native';

export const Colors = {
  light: {
    text: '#000000',
    background: '#ffffff',
    backgroundElement: '#F0F0F3',
    backgroundSelected: '#E0E1E6',
    textSecondary: '#60646C',
  },
  dark: {
    text: '#ffffff',
    background: '#000000',
    backgroundElement: '#212225',
    backgroundSelected: '#2E3135',
    textSecondary: '#B0B4BA',
  },
} as const;

export type ThemeColor = keyof typeof Colors.light & keyof typeof Colors.dark;

export const Fonts = Platform.select({
  ios: {
    sans: 'system-ui',
    serif: 'ui-serif',
    rounded: 'ui-rounded',
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: 'Spline Sans, Inter, ui-sans-serif, system-ui, sans-serif',
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
  },
});

export const Spacing = {
  half: 2,
  one: 4,
  two: 8,
  three: 16,
  four: 24,
  five: 32,
  six: 64,
} as const;

export const BottomTabInset = Platform.select({ ios: 50, android: 80 }) ?? 0;
export const MaxContentWidth = 800;

export const appColors = {
  backgroundTop: '#102b56',
  backgroundBottom: '#02112b',
  backgroundPanel: '#102b56',
  backgroundDeep: '#02112b',
  backgroundCard: 'rgba(255,255,255,0.05)',
  backgroundCardStrong: 'rgba(0,0,0,0.3)',
  overlay: 'rgba(0,0,0,0.75)',
  overlayStrong: 'rgba(0,0,0,0.85)',
  textPrimary: '#ffffff',
  textMuted: 'rgba(255,255,255,0.6)',
  textSoft: 'rgba(255,255,255,0.4)',
  textFaint: 'rgba(255,255,255,0.3)',
  textInverse: '#02112b',
  placeholder: '#666666',
  placeholderLight: 'rgba(255,255,255,0.3)',
  transparent: 'transparent',
  neutral: '#666666',
  primary: '#00bfff',
  primaryDark: '#02112b',
  primarySoft: 'rgba(0,191,255,0.1)',
  success: '#00fa9a',
  successSoft: 'rgba(0,250,154,0.1)',
  danger: '#ff6666',
  dangerSoft: 'rgba(255,50,50,0.1)',
  warning: '#ffd700',
  warningSoft: 'rgba(255,215,0,0.1)',
  silver: '#c0c0c0',
  copper: '#cd7f32',
  black: '#000000',
  dieD4: '#ff9f43',
  dieD6: '#ff4757',
  dieD8: '#2ed573',
  dieD10: '#1dd1a1',
  dieD12: '#9b59b6',
  dieD20: '#1e90ff',
  dieD100: '#576574',
} as const;

export const appGradients = {
  main: [appColors.backgroundTop, appColors.backgroundBottom] as const,
} as const;

export const appFonts = Fonts;

export const appFontSizes = {
  tiny: 8,
  caption: 10,
  small: 12,
  body: 14,
  input: 16,
  title: 20,
  display: 32,
} as const;

export const appSpacing = Spacing;

export const diceFabSize = 60;

export const layoutStyles = StyleSheet.create({
  root: { flex: 1 },
  transparentContent: { backgroundColor: appColors.transparent },
});

export const qrCodeStyles = StyleSheet.create({
  qrBox: {
    alignSelf: 'center',
    backgroundColor: appColors.textPrimary,
    overflow: 'hidden',
  },
  qrRow: {
    flexDirection: 'row',
  },
  qrCell: {
    backgroundColor: appColors.textPrimary,
  },
  qrCellDark: {
    backgroundColor: appColors.black,
  },
});

export const sheetStyles = StyleSheet.create({
  container: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#02112b' },
  errorText: { color: '#ff6666', fontWeight: 'bold' },
  topBar: { paddingTop: 60, paddingBottom: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(0,0,0,0.2)', position: 'relative' },
  topBarBack: { position: 'absolute', left: 20, bottom: 12, padding: 5, zIndex: 10 },
  topBarBackText: { color: '#00bfff', fontSize: 16, fontWeight: 'bold' },
  topBarTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  
  tabContainer: { paddingHorizontal: 20, paddingBottom: 10, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.05)' },
  tab: { paddingVertical: 12, paddingHorizontal: 15, alignItems: 'center', marginRight: 10 },
  activeTab: { borderBottomWidth: 2, borderBottomColor: '#00bfff' },
  tabText: { color: 'rgba(255,255,255,0.4)', fontWeight: 'bold', fontSize: 12, letterSpacing: 1 },
  activeTabText: { color: '#00bfff' },
  
  scrollContent: { padding: 20 },
  
  headerBlock: { alignItems: 'center', marginBottom: 20 },
  charClassRace: { fontSize: 14, color: '#00bfff' },
  levelXpRow: { flexDirection: 'row', gap: 10, marginTop: 10, alignItems: 'center' },
  badge: { backgroundColor: 'rgba(0,191,255,0.1)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 10 },
  badgeText: { color: '#00bfff', fontSize: 11, fontWeight: 'bold' },
  
  levelUpIconBtn: { paddingHorizontal: 5, justifyContent: 'center', alignItems: 'center' },

  hpBarStyle: { backgroundColor: 'rgba(255,50,50,0.1)', padding: 20, borderRadius: 20, alignItems: 'center', marginBottom: 15 },
  hpTextStyle: { fontSize: 36, fontWeight: 'bold', color: '#ff6666' },
  hpMaxTextStyle: { fontSize: 20, color: 'rgba(255,102,102,0.4)' },
  combatLabel: { fontSize: 9, color: 'rgba(255,255,255,0.5)', marginTop: 5, letterSpacing: 1, fontWeight: 'bold' },
  combatStatsRow: { flexDirection: 'row', gap: 10, marginBottom: 20 },
  combatStatSmall: { flex: 1, backgroundColor: 'rgba(255,255,255,0.05)', padding: 15, borderRadius: 15, alignItems: 'center' },
  combatStatValue: { fontSize: 18, color: '#fff', fontWeight: 'bold' },
  
  sectionTitle: { color: '#00bfff', fontWeight: 'bold', marginTop: 10, marginBottom: 10, fontSize: 12 },
  attributesGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  attrBox: { width: '31%', backgroundColor: 'rgba(255,255,255,0.05)', padding: 15, borderRadius: 15, alignItems: 'center', marginBottom: 15 },
  attrLabel: { fontSize: 9, color: 'rgba(255,255,255,0.5)', marginBottom: 5 },
  attrValue: { fontSize: 20, color: '#fff', fontWeight: 'bold' },
  modBadge: { backgroundColor: '#00bfff', paddingHorizontal: 8, borderRadius: 6, marginTop: 5 },
  modText: { fontSize: 12, fontWeight: 'bold', color: '#02112b' },
  
  cardBlock: { backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 20, padding: 15, marginTop: 5, marginBottom: 15 },
  detailSection: { marginBottom: 15 },
  detailLabel: { fontSize: 10, color: 'rgba(0,191,255,0.5)', fontWeight: 'bold', marginBottom: 5 },
  detailText: { color: '#fff', fontSize: 14, lineHeight: 20 },

  profRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.05)' },
  profStatBadge: { backgroundColor: 'rgba(255,255,255,0.1)', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 5, marginRight: 10, width: 35, alignItems: 'center' },
  profIconActive: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#00bfff', marginRight: 10 },
  profName: { color: '#fff', fontSize: 13 },
  profValue: { color: '#fff', fontWeight: 'bold', fontSize: 14 },

  weightCard: { backgroundColor: 'rgba(255,255,255,0.05)', padding: 10, borderRadius: 15, marginBottom: 15, alignItems: 'center' },
  weightVal: { fontSize: 18, color: '#fff', fontWeight: 'bold', marginTop: 5 },
  weightBarStyle: { width: '100%', height: 4, backgroundColor: 'rgba(255,255,255,0.1)', borderRadius: 2, marginTop: 5 },
  weightFillStyle: { height: '100%', borderRadius: 2 },
  atkCard: { backgroundColor: 'rgba(0,191,255,0.1)', padding: 15, borderRadius: 16, alignItems: 'center', marginBottom: 10 },
  atkRow: { flexDirection: 'row', marginTop: 10, gap: 40 },
  atkSubBox: { alignItems: 'center' },
  atkVal: { fontSize: 20, color: '#fff', fontWeight: 'bold' },
  atkLab: { fontSize: 8, color: '#00bfff', fontWeight: 'bold', marginTop: 3 },
  
  equipGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 10, marginBottom: 20 },
  equipSlotBox: { width: '48%', backgroundColor: 'rgba(0,0,0,0.3)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', borderRadius: 12, padding: 15, alignItems: 'center', justifyContent: 'center', height: 95 },
  equipSlotBoxFilled: { borderColor: '#00bfff', backgroundColor: 'rgba(0,191,255,0.05)' },
  equipSlotLabel: { fontSize: 8, color: 'rgba(255,255,255,0.5)', position: 'absolute', top: 8, left: 8, fontWeight: 'bold' },
  equipSlotEmptyIcon: { fontSize: 30, opacity: 0.2 },
  equipSlotItemName: { color: '#fff', fontWeight: 'bold', textAlign: 'center', fontSize: 13, marginTop: 5 },
  equipSlotItemDamage: { color: '#00fa9a', fontSize: 10, marginTop: 5, fontWeight: 'bold' },

  coinManager: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  coinControl: { flex: 1, backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 12, padding: 8, alignItems: 'center' },
  coinDisplay: { alignItems: 'center', marginVertical: 5 },
  coinLabel: { fontSize: 10, fontWeight: 'bold' },
  coinValText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  coinBtn: { width: '100%', paddingVertical: 5, alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.1)', borderRadius: 8 },
  qtyBtnText: { color: '#00bfff', fontSize: 20, fontWeight: 'bold' },
  headerSpaceBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  addBtn: { backgroundColor: '#00bfff', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  addBtnText: { color: '#02112b', fontWeight: 'bold', fontSize: 11 },
  itemRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.05)' },
  qtyContainer: { flexDirection: 'row', alignItems: 'center', gap: 8, marginRight: 15 },
  itemQty: { color: '#fff', fontWeight: 'bold', width: 15, textAlign: 'center', fontSize: 14 },
  smallQtyBtn: { width: 28, height: 28, backgroundColor: 'rgba(0,191,255,0.1)', borderRadius: 6, justifyContent: 'center', alignItems: 'center' },
  smallQtyBtnText: { color: '#00bfff', fontSize: 16, fontWeight: 'bold' },
  itemName: { color: '#fff', fontSize: 15, fontWeight: '500' },
  itemSubDetail: { color: 'rgba(255,255,255,0.4)', fontSize: 10, marginTop: 2 },
  emptyText: { color: 'rgba(255,255,255,0.3)', textAlign: 'center', marginVertical: 20, fontSize: 12 },
  sessionPartyBox: { backgroundColor: 'rgba(0,0,0,0.25)', borderWidth: 1, borderColor: 'rgba(0,191,255,0.18)', borderRadius: 16, padding: 14, marginBottom: 16 },
  sessionPartyHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12, marginBottom: 10 },
  sessionPartyTitle: { color: '#00bfff', fontSize: 12, fontWeight: 'bold', letterSpacing: 1 },
  sessionPartyHint: { color: 'rgba(255,255,255,0.45)', fontSize: 11 },
  sessionPlayerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, paddingVertical: 9, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.06)' },
  sessionPlayerName: { color: '#fff', fontSize: 13, fontWeight: 'bold' },
  sessionPlayerMeta: { color: 'rgba(255,255,255,0.5)', fontSize: 11, marginTop: 2 },
  sessionHpBox: { minWidth: 86, alignItems: 'flex-end' },
  sessionHpText: { color: '#ff6666', fontSize: 13, fontWeight: 'bold' },
  sessionHpTrack: { width: 74, height: 5, borderRadius: 99, backgroundColor: 'rgba(255,102,102,0.15)', overflow: 'hidden', marginTop: 4 },
  sessionHpFill: { height: '100%', borderRadius: 99, backgroundColor: '#ff6666' },
  pendingTradeButton: { backgroundColor: 'rgba(255,215,0,0.1)', borderWidth: 1, borderColor: 'rgba(255,215,0,0.35)', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 7 },
  pendingTradeText: { color: '#ffd700', fontSize: 11, fontWeight: 'bold' },
  tradePanel: { backgroundColor: '#02112b', width: '92%', maxHeight: '88%', borderRadius: 18, padding: 18, borderWidth: 1, borderColor: 'rgba(0,191,255,0.35)' },
  tradeBoard: { flexDirection: 'row', gap: 10, marginVertical: 12 },
  tradeColumn: { flex: 1, backgroundColor: 'rgba(255,255,255,0.04)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', borderRadius: 12, padding: 10, minHeight: 170 },
  tradeColumnTitle: { color: '#00bfff', fontSize: 11, fontWeight: 'bold', marginBottom: 8, textTransform: 'uppercase' },
  tradeSlot: { borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)', borderRadius: 10, minHeight: 72, padding: 10, justifyContent: 'center' },
  tradeSlotActive: { borderColor: '#00fa9a', backgroundColor: 'rgba(0,250,154,0.08)' },
  tradeSlotName: { color: '#fff', fontSize: 13, fontWeight: 'bold' },
  tradeSlotMeta: { color: 'rgba(255,255,255,0.45)', fontSize: 11, marginTop: 4 },
  tradeArrowBox: { alignItems: 'center', justifyContent: 'center', width: 26 },
  tradeList: { maxHeight: 220, marginTop: 8 },
  tradeItemChoice: { borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', borderRadius: 10, padding: 10, marginBottom: 8, backgroundColor: 'rgba(0,0,0,0.2)' },
  tradeItemChoiceActive: { borderColor: '#00fa9a', backgroundColor: 'rgba(0,250,154,0.08)' },
  tradeActionButton: { flexDirection: 'row', backgroundColor: 'rgba(0,191,255,0.1)', paddingVertical: 13, borderRadius: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(0,191,255,0.3)', gap: 8 },
  tradeActionButtonText: { color: '#00bfff', fontWeight: 'bold', fontSize: 15 },
  spellCastPanel: { backgroundColor: '#02112b', width: '92%', maxHeight: '88%', borderRadius: 18, padding: 18, borderWidth: 1, borderColor: 'rgba(0,191,255,0.35)' },
  spellCastHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12, marginBottom: 12 },
  spellCastTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold', flex: 1 },
  spellCastMeta: { color: 'rgba(255,255,255,0.5)', fontSize: 11, marginTop: 4 },
  spellTargetRow: { flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', borderRadius: 12, padding: 10, marginBottom: 8, backgroundColor: 'rgba(0,0,0,0.2)' },
  spellTargetRowActive: { borderColor: '#00fa9a', backgroundColor: 'rgba(0,250,154,0.08)' },
  spellTargetCheck: { width: 24, height: 24, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.25)', alignItems: 'center', justifyContent: 'center' },
  spellTargetCheckActive: { backgroundColor: '#00fa9a', borderColor: '#00fa9a' },
  spellAmountInput: { width: 68, color: '#fff', textAlign: 'center', backgroundColor: 'rgba(0,0,0,0.3)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)', borderRadius: 10, paddingVertical: 8, paddingHorizontal: 8, fontSize: 15, fontWeight: 'bold' },
  spellResultBox: { backgroundColor: 'rgba(0,191,255,0.08)', borderWidth: 1, borderColor: 'rgba(0,191,255,0.22)', borderRadius: 10, padding: 10, marginVertical: 10 },
  spellResultText: { color: '#00bfff', fontSize: 12, fontWeight: 'bold', textAlign: 'center' },
  spellEffectRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8, marginBottom: 8 },

  // BOTÕES DA MOCHILA E AÇÕES
  iconActionBtn: { padding: 8, borderRadius: 8, backgroundColor: 'rgba(0,250,154,0.1)', borderWidth: 1, borderColor: 'rgba(0,250,154,0.3)', justifyContent: 'center', alignItems: 'center' },

  itemStatsBox: { backgroundColor: 'rgba(0,0,0,0.3)', padding: 10, borderRadius: 8, marginBottom: 15, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)', alignItems: 'center' },
  itemStatText: { color: '#00fa9a', fontSize: 13, marginBottom: 5, fontWeight: 'bold' },

  spellFilterSection: { backgroundColor: 'rgba(255,255,255,0.05)', padding: 15, borderRadius: 20, marginBottom: 15 },
  spellSearchRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 15 },
  spellSearchInputBox: { flex: 1, flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.3)', borderRadius: 12, paddingHorizontal: 15, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  spellSearchInput: { flex: 1, color: '#fff', paddingVertical: 10, marginLeft: 10, fontSize: 14 },
  spellSortBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(0,191,255,0.1)', paddingHorizontal: 12, paddingVertical: 10, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(0,191,255,0.3)', gap: 5 },
  spellSortText: { color: '#00bfff', fontWeight: 'bold', fontSize: 12 },
  filterLabel: { fontSize: 10, color: '#00bfff', fontWeight: 'bold', marginBottom: 8, letterSpacing: 1 },
  filterPill: { paddingVertical: 6, paddingHorizontal: 15, borderRadius: 20, backgroundColor: 'rgba(0,0,0,0.3)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  filterPillActive: { backgroundColor: 'rgba(0,191,255,0.2)', borderColor: '#00bfff' },
  filterPillText: { color: 'rgba(255,255,255,0.5)', fontSize: 11, fontWeight: 'bold' },
  filterPillTextActive: { color: '#00bfff' },

  // NOVOS ESTILOS COMPACTOS PARA MAGIAS E MODAL
  spellGroupHeader: { color: 'rgba(255,255,255,0.6)', fontWeight: 'bold', fontSize: 14, letterSpacing: 1 },
  spellCardCompact: { flexDirection: 'row', backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 16, padding: 15, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', alignItems: 'center', flex: 1 },
  spellIconBox: { width: 45, height: 45, borderRadius: 12, backgroundColor: 'rgba(0,0,0,0.3)', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(0,191,255,0.3)' },
  spellNameCompact: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  spellSubCompact: { color: 'rgba(255,255,255,0.5)', fontSize: 11, marginTop: 4 },
  
  spellDetailCard: { backgroundColor: '#102b56', borderRadius: 24, padding: 25, width: '90%', borderWidth: 1, borderColor: '#00bfff', alignSelf: 'center', marginTop: 'auto', marginBottom: 'auto' },
  spellDetailHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 15 },
  spellDetailIcon: { width: 50, height: 50, borderRadius: 15, backgroundColor: '#00bfff', justifyContent: 'center', alignItems: 'center' },
  spellDetailName: { color: '#fff', fontSize: 20, fontWeight: 'bold', marginBottom: 2 },
  spellDetailLevel: { color: '#00bfff', fontSize: 11, fontWeight: 'bold', textTransform: 'uppercase' },
  divider: { height: 1, backgroundColor: 'rgba(255,255,255,0.1)', marginBottom: 15 },
  spellDetailInfoGrid: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 15, backgroundColor: 'rgba(0,0,0,0.2)', padding: 12, borderRadius: 12 },
  spellDetailInfoItem: { alignItems: 'center', flex: 1 },
  spellDetailInfoLabel: { color: 'rgba(255,255,255,0.4)', fontSize: 9, fontWeight: 'bold', letterSpacing: 1, marginBottom: 4 },
  spellDetailInfoValue: { color: '#fff', fontSize: 13, fontWeight: 'bold', textAlign: 'center' },
  spellDetailDescription: { color: 'rgba(255,255,255,0.8)', fontSize: 14, lineHeight: 22 },

  // NOVOS ESTILOS PARA CÂMBIO DE MOEDAS
  exchangeBox: { flexDirection: 'row', backgroundColor: 'rgba(0,0,0,0.3)', padding: 15, borderRadius: 16, alignItems: 'center', justifyContent: 'space-between', marginBottom: 20, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  exchangeSide: { alignItems: 'center', flex: 1 },
  exchangeLabel: { fontSize: 10, color: 'rgba(255,255,255,0.5)', fontWeight: 'bold', marginBottom: 8, letterSpacing: 1 },
  exchangeCoins: { flexDirection: 'row', gap: 5 },
  coinMiniBtn: { width: 34, height: 34, borderRadius: 17, borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.02)' },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalContent: { backgroundColor: '#102b56', width: '100%', borderRadius: 25, padding: 20, borderWidth: 1, borderColor: 'rgba(0,191,255,0.3)' },
  modalTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold', textAlign: 'center', marginBottom: 5 },
  modalInput: { backgroundColor: 'rgba(255,255,255,0.1)', padding: 15, borderRadius: 15, color: '#fff', fontSize: 16, marginBottom: 15 },
  modalInputLarge: { backgroundColor: 'rgba(255,255,255,0.1)', padding: 15, borderRadius: 15, color: '#fff', fontSize: 24, textAlign: 'center', marginBottom: 15, fontWeight: 'bold' },
  modalRowButtons: { flexDirection: 'row', gap: 10 },
  modalBtn: { flex: 1, padding: 15, alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 15 },
  
  lvlUpBtnPrimary: { backgroundColor: '#00bfff', paddingVertical: 14, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  lvlUpBtnPrimaryText: { color: '#000000', fontWeight: 'bold', fontSize: 16 }, 
  lvlUpBtnSecondary: { backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', paddingVertical: 14, borderRadius: 12, alignItems: 'center' },
  lvlUpBtnSecondaryText: { color: '#ffffff', fontWeight: 'bold', fontSize: 14 },

  catalogItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.05)' },
  catalogItemName: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  catalogItemSub: { color: 'rgba(0,191,255,0.5)', fontSize: 12, marginTop: 2 },
  addIcon: { color: '#00bfff', fontSize: 24, fontWeight: 'bold' },
  unequipBtn: { backgroundColor: 'rgba(255,50,50,0.1)', padding: 10, borderRadius: 10, alignItems: 'center', marginBottom: 15, borderWidth: 1, borderColor: 'rgba(255,50,50,0.3)' },
  unequipBtnText: { color: '#ff6666', fontWeight: 'bold', fontSize: 12 },

  actionModalBox: { backgroundColor: '#02112b', width: '85%', borderRadius: 25, padding: 25, borderWidth: 1, borderColor: '#00bfff' },
  actionQtyRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 20, marginVertical: 10 },
  actionQtyBtn: { backgroundColor: 'rgba(255,255,255,0.1)', width: 45, height: 45, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  actionQtyBtnText: { color: '#00bfff', fontSize: 26, fontWeight: 'bold' },
  actionQtyVal: { color: '#fff', fontSize: 28, fontWeight: 'bold', width: 50, textAlign: 'center' },
  
  actionBtnConsume: { flexDirection: 'row', backgroundColor: 'rgba(0,250,154,0.1)', paddingVertical: 15, borderRadius: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(0,250,154,0.3)', gap: 10 },
  actionBtnConsumeText: { color: '#00fa9a', fontWeight: 'bold', fontSize: 16 },
  actionBtnThrow: { flexDirection: 'row', backgroundColor: 'rgba(255,100,100,0.1)', paddingVertical: 15, borderRadius: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,100,100,0.3)', gap: 10 },
  actionBtnThrowText: { color: '#ff6666', fontWeight: 'bold', fontSize: 16 },
  actionBtnCancel: { paddingVertical: 15, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  actionBtnCancelText: { color: 'rgba(255,255,255,0.5)', fontWeight: 'bold', fontSize: 14 },

  customAlertBox: { backgroundColor: '#102b56', width: '90%', borderRadius: 20, padding: 25, borderWidth: 1, borderColor: 'rgba(0,191,255,0.3)', alignItems: 'center' },
  customAlertTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold', marginBottom: 15, textAlign: 'center' },
  customAlertMessage: { color: 'rgba(255,255,255,0.8)', fontSize: 14, textAlign: 'center', lineHeight: 22, marginBottom: 25 },
  customAlertBtnRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, width: '100%', justifyContent: 'center' },
  customAlertBtn: { paddingVertical: 12, paddingHorizontal: 20, borderRadius: 10, alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.05)', minWidth: '30%' },
  customAlertBtnText: { fontWeight: 'bold', fontSize: 14 },
  modalCloseButton: { marginTop: 20, paddingVertical: 15, width: '100%', alignItems: 'center', backgroundColor: 'rgba(255, 255, 255, 0.05)', borderRadius: 12 },
  modalCloseText: { color: '#00bfff', fontWeight: 'bold' }
});

export const editStyles = StyleSheet.create({
  container: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#02112b' },
  topBar: { paddingTop: 50, paddingBottom: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, backgroundColor: 'rgba(0,0,0,0.3)' },
  topBarTitle: { color: '#ffd700', fontSize: 16, fontWeight: 'bold' },
  stepIndicatorText: { color: '#fff', fontSize: 12 },
  progressBarContainer: { flexDirection: 'row', height: 4, backgroundColor: 'rgba(0,0,0,0.5)' },
  progressSegment: { flex: 1, backgroundColor: 'transparent' },
  progressSegmentActive: { backgroundColor: '#00bfff' },
  scrollContent: { padding: 20 },
  sectionTitle: { color: '#00bfff', fontWeight: 'bold', marginBottom: 15, fontSize: 12, textTransform: 'uppercase' },
  cardBlock: { backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 20, padding: 20, marginBottom: 20 },
  
  classManagerBox: { marginBottom: 20, backgroundColor: 'rgba(0,0,0,0.2)', padding: 15, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  classHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  classTitleName: { color: '#fff', fontSize: 18, fontWeight: 'bold', flex: 1, marginLeft: 10 },
  qtyControl: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.1)', borderRadius: 8 },
  qtyBtn: { paddingHorizontal: 12, paddingVertical: 5 },
  qtyBtnText: { color: '#00bfff', fontSize: 20, fontWeight: 'bold' },
  qtyValue: { color: '#fff', fontSize: 16, fontWeight: 'bold', width: 25, textAlign: 'center' },

  subclassGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 15, justifyContent: 'center' },
  subclassBtn: { backgroundColor: 'rgba(255,255,255,0.05)', padding: 10, borderRadius: 12, borderWidth: 1, borderColor: '#444' },
  subclassBtnActive: { borderColor: '#00bfff', backgroundColor: 'rgba(0,191,255,0.1)' },
  subclassBtnText: { color: '#fff', fontSize: 11 },
  subclassBtnTextActive: { color: '#00bfff', fontWeight: 'bold' },
  
  multiclassBtn: { padding: 15, borderRadius: 12, borderWidth: 1, borderColor: '#00bfff', borderStyle: 'dashed', alignItems: 'center' },
  multiclassBtnText: { color: '#00bfff', fontSize: 13, fontWeight: 'bold' },

  hpRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 20 },
  hpInfoBox: { alignItems: 'center' },
  hpInputBox: { alignItems: 'center' },
  hpLabel: { color: '#aaa', fontSize: 10, marginBottom: 5 },
  hpValue: { color: '#fff', fontSize: 32, fontWeight: 'bold' },
  hpInput: { backgroundColor: '#000', color: '#00fa9a', fontSize: 28, width: 80, textAlign: 'center', borderRadius: 12, padding: 5, borderWidth: 1, borderColor: 'rgba(0,250,154,0.3)' },
  hpPlusIcon: { color: '#00fa9a', fontSize: 24 },
  hpHint: { color: 'rgba(255,255,255,0.5)', fontSize: 12, textAlign: 'center', marginTop: 15, lineHeight: 18 },
  recommendedBtn: { marginTop: 15, padding: 12, backgroundColor: 'rgba(0, 250, 154, 0.1)', borderRadius: 10, alignItems: 'center', borderWidth: 1, borderColor: '#00fa9a' },
  recommendedBtnText: { color: '#00fa9a', fontSize: 12, fontWeight: 'bold' },
  
  warningBox: { backgroundColor: 'rgba(0,191,255,0.1)', padding: 15, borderRadius: 12, flexDirection: 'row', alignItems: 'center', gap: 15, marginBottom: 15, borderWidth: 1, borderColor: 'rgba(0,191,255,0.3)' },
  warningText: { color: '#00bfff', flex: 1, fontSize: 12, lineHeight: 18 },

  counterText: { fontSize: 12, fontWeight: 'bold', color: '#00bfff', backgroundColor: 'rgba(0, 191, 255, 0.1)', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8 },
  
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  statEditorBox: { width: '48%', backgroundColor: 'rgba(0,0,0,0.3)', padding: 15, borderRadius: 15, alignItems: 'center', marginBottom: 15, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  statLabel: { color: '#00bfff', fontSize: 12, fontWeight: 'bold', marginBottom: 10 },
  statControlRow: { flexDirection: 'row', alignItems: 'center', gap: 15, marginVertical: 5 },
  statBtn: { padding: 5, backgroundColor: 'rgba(255,255,255,0.1)', borderRadius: 8, width: 35, alignItems: 'center' },
  statBtnText: { color: '#fff', fontSize: 20, fontWeight: 'bold' },
  statValText: { color: '#fff', fontSize: 22, fontWeight: 'bold', width: 35, textAlign: 'center' },
  statModLabel: { color: 'rgba(255,255,255,0.4)', fontSize: 10, fontWeight: 'bold', marginTop: 5 },
  
  toggleGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  toggleBtn: { paddingVertical: 10, paddingHorizontal: 12, borderRadius: 12, backgroundColor: 'rgba(0,0,0,0.3)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  toggleBtnActive: { backgroundColor: '#00bfff', borderColor: '#00bfff' },
  toggleBtnText: { color: 'rgba(255,255,255,0.6)', fontSize: 12, fontWeight: 'bold' },
  toggleBtnTextActive: { color: '#02112b' },

  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  summaryLabel: { color: 'rgba(255,255,255,0.6)', fontSize: 14, fontWeight: 'bold' },
  summaryValue: { color: '#fff', fontSize: 16, fontWeight: 'bold' },

  spellHeaderRow: { marginBottom: 5, backgroundColor: 'rgba(0,0,0,0.2)', padding: 10, borderRadius: 8, alignItems: 'center' },
  manageSpellsBtn: { backgroundColor: '#00bfff', padding: 18, borderRadius: 15, alignItems: 'center', marginTop: 10 },
  manageSpellsBtnText: { color: '#02112b', fontWeight: 'bold', fontSize: 14 },
  
  summarySpellItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.05)', paddingHorizontal: 15, paddingVertical: 10, borderRadius: 8, marginBottom: 5 },

  bottomNav: { flexDirection: 'row', padding: 20, gap: 10, backgroundColor: '#02112b', borderTopWidth: 1, borderTopColor: '#333' },
  navBtn: { flex: 1, padding: 16, borderRadius: 12, alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.05)' },
  navBtnPrimary: { backgroundColor: '#00bfff' },
  navBtnFinish: { backgroundColor: '#00fa9a' },
  navBtnText: { color: '#fff', fontWeight: 'bold' },
  navBtnPrimaryText: { color: '#02112b', fontWeight: 'bold' },
  navBtnFinishText: { color: '#02112b', fontWeight: 'bold', fontSize: 16 },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'flex-end' },
  modalContentFullScreen: { backgroundColor: '#102b56', borderTopLeftRadius: 30, borderTopRightRadius: 30, padding: 20, maxHeight: '90%', borderWidth: 1, borderColor: 'rgba(0,191,255,0.3)' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  modalTitle: { color: '#fff', fontSize: 20, fontWeight: 'bold' },

  spellItemRow: { flexDirection: 'row', alignItems: 'center', padding: 5, backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 12, marginBottom: 8, justifyContent: 'space-between' },
  spellItemName: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
});

export const createStyles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: { padding: 20, paddingTop: 60, paddingBottom: 100 },
  header: { marginBottom: 30, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  headerTitle: { fontSize: 32, fontWeight: 'bold', color: '#ffffff' },
  headerSubtitle: { fontSize: 16, color: '#00bfff', marginTop: 5, fontWeight: 'bold' },
  randomDiceBtn: { backgroundColor: 'rgba(255,255,255,0.1)', padding: 12, borderRadius: 16, borderWidth: 1, borderColor: 'rgba(255,255,255,0.3)', alignItems: 'center', justifyContent: 'center' },
  formGroup: { marginBottom: 20 },
  row: { flexDirection: 'row', justifyContent: 'space-between' },
  label: { fontSize: 12, fontWeight: 'bold', color: 'rgba(255, 255, 255, 0.7)', marginBottom: 8, letterSpacing: 1 },
  input: { backgroundColor: 'rgba(255, 255, 255, 0.05)', borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.1)', borderRadius: 12, paddingHorizontal: 15, paddingVertical: 12, fontSize: 16, color: '#ffffff' },
  textArea: { backgroundColor: 'rgba(255, 255, 255, 0.05)', borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.1)', borderRadius: 12, paddingHorizontal: 15, paddingVertical: 15, fontSize: 14, color: '#ffffff', minHeight: 100, textAlignVertical: 'top' },
  selectButton: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: 'rgba(255, 255, 255, 0.05)', borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.1)', borderRadius: 12, paddingHorizontal: 15, paddingVertical: 16 },
  selectButtonText: { fontSize: 16, color: '#ffffff' },
  selectIcon: { color: 'rgba(255, 255, 255, 0.5)', fontSize: 12 },
  modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0, 0, 0, 0.8)' },
  modalOverlayCenter: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0, 0, 0, 0.8)', padding: 20 },
  modalContent: { backgroundColor: '#102b56', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, alignItems: 'center', width: '100%', borderWidth: 1, borderColor: '#00bfff' },
  modalTitle: { fontSize: 18, fontWeight: 'bold', color: '#ffffff', marginBottom: 15 },
  searchInput: { width: '100%', backgroundColor: 'rgba(255, 255, 255, 0.1)', borderRadius: 12, padding: 12, color: '#ffffff', fontSize: 16, marginBottom: 15 },
  modalListItem: { width: '100%', paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: 'rgba(255, 255, 255, 0.05)' },
  modalListItemText: { fontSize: 16, color: '#ffffff' },
  emptyText: { color: 'rgba(255, 255, 255, 0.5)', marginTop: 20, textAlign: 'center' },
  modalCloseButton: { marginTop: 20, paddingVertical: 12, width: '100%', alignItems: 'center', backgroundColor: 'rgba(255, 255, 255, 0.05)', borderRadius: 12 },
  modalCloseText: { color: '#00bfff', fontWeight: 'bold' },
  statsHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', color: '#ffffff' },
  counterText: { fontSize: 12, fontWeight: 'bold', color: '#00bfff', backgroundColor: 'rgba(0, 191, 255, 0.1)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  statsSection: { marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderTopColor: 'rgba(255, 255, 255, 0.1)' },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 10 },
  statBox: { width: '30%', backgroundColor: 'rgba(255, 255, 255, 0.05)', borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.1)', borderRadius: 12, padding: 10, alignItems: 'center' },
  statLabel: { fontSize: 14, fontWeight: 'bold', color: 'rgba(255, 255, 255, 0.7)', marginBottom: 5 },
  statInput: { fontSize: 24, fontWeight: 'bold', color: '#ffffff', textAlign: 'center' },
  stepContainer: { marginTop: 10 },
  step2Container: { marginTop: 10 },
  profBonusHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: 'rgba(0, 191, 255, 0.1)', borderWidth: 1, borderColor: 'rgba(0, 191, 255, 0.3)', borderRadius: 12, padding: 15, marginBottom: 20 },
  profBonusTitle: { fontSize: 14, fontWeight: 'bold', color: '#ffffff' },
  profBonusInput: { fontSize: 20, fontWeight: 'bold', color: '#00bfff', backgroundColor: 'rgba(0, 0, 0, 0.2)', paddingHorizontal: 15, paddingVertical: 5, borderRadius: 8 },
  listTitle: { fontSize: 14, fontWeight: 'bold', color: '#ffffff' },
  skillsCard: { backgroundColor: 'rgba(255, 255, 255, 0.05)', borderRadius: 16, padding: 15, marginBottom: 20 },
  skillRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: 'rgba(255, 255, 255, 0.05)' },
  radioCircle: { height: 24, width: 24, borderRadius: 12, borderWidth: 2, borderColor: 'rgba(255, 255, 255, 0.3)', alignItems: 'center', justifyContent: 'center', marginRight: 15 },
  radioCircleSelected: { borderColor: '#00bfff' },
  radioDot: { height: 12, width: 12, borderRadius: 6, backgroundColor: '#00bfff' },
  skillInputCalculated: { width: 40, fontSize: 16, fontWeight: 'bold', color: '#00bfff', textAlign: 'center', marginRight: 10 },
  skillName: { fontSize: 16, color: 'rgba(255, 255, 255, 0.8)' },
  spellLevelHint: { fontSize: 10, fontWeight: 'bold', color: '#00bfff', backgroundColor: 'rgba(0, 191, 255, 0.1)', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  statHint: { fontSize: 12, color: 'rgba(255, 255, 255, 0.4)' },
  footer: { position: 'absolute', bottom: 30, left: 20, right: 20, flexDirection: 'row', gap: 10 },
  backButton: { flex: 1, backgroundColor: 'transparent', borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.3)', borderRadius: 16, paddingVertical: 18, alignItems: 'center' },
  backButtonText: { fontSize: 14, fontWeight: 'bold', color: '#ffffff' },
  primaryButton: { flex: 2, backgroundColor: '#00bfff', borderRadius: 16, paddingVertical: 18, alignItems: 'center' },
  primaryButtonText: { fontSize: 14, fontWeight: 'bold', color: '#02112b' },
  infoBox: { backgroundColor: 'rgba(0, 191, 255, 0.1)', padding: 15, borderRadius: 12, borderColor: 'rgba(0, 191, 255, 0.3)', borderWidth: 1, marginBottom: 20 },
  hpHint: { color: 'rgba(255,255,255,0.5)', fontSize: 12, textAlign: 'center', marginTop: 5, marginBottom: 15, lineHeight: 18 },
  infoText: { color: '#ffffff', fontSize: 14, lineHeight: 20 },
  qtyControl: { flexDirection: 'row', alignItems: 'center', marginRight: 15, backgroundColor: 'rgba(255, 255, 255, 0.1)', borderRadius: 8 },
  qtyBtn: { paddingHorizontal: 12, paddingVertical: 6 },
  qtyBtnText: { color: '#00bfff', fontSize: 18, fontWeight: 'bold' },
  qtyValue: { color: '#ffffff', fontSize: 16, fontWeight: 'bold', width: 20, textAlign: 'center' },
  coinsRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20, gap: 10 },
  coinBox: { flex: 1, backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 12, padding: 10, alignItems: 'center' },
  coinLabel: { fontSize: 10, fontWeight: 'bold', marginBottom: 5 },
  coinInput: { color: '#fff', fontSize: 18, fontWeight: 'bold', textAlign: 'center' },
  summaryHeader: { alignItems: 'center', marginBottom: 20, backgroundColor: 'rgba(255, 255, 255, 0.05)', padding: 20, borderRadius: 16 },
  summaryName: { fontSize: 28, fontWeight: 'bold', color: '#fff', marginBottom: 5 },
  summarySubtitle: { fontSize: 16, color: '#00bfff', fontWeight: 'bold' },
  summaryGrid: { flexDirection: 'row', justifyContent: 'space-between', gap: 10, marginBottom: 10 },
  summaryBox: { flex: 1, backgroundColor: 'rgba(0, 191, 255, 0.05)', paddingVertical: 15, borderRadius: 12, alignItems: 'center' },
  summaryBoxValue: { fontSize: 26, fontWeight: 'bold', color: '#fff' },
  summaryBoxLabel: { fontSize: 10, fontWeight: 'bold', color: '#00bfff' },
  hpContainer: { flexDirection: 'row', justifyContent: 'space-between', gap: 10, marginBottom: 20 },
  hpBox: { flex: 1, backgroundColor: 'rgba(255, 50, 50, 0.05)', paddingVertical: 15, borderRadius: 12, alignItems: 'center' },
  hpValue: { fontSize: 26, fontWeight: 'bold', color: '#ff6666' },
  hpLabel: { fontSize: 10, fontWeight: 'bold', color: 'rgba(255, 255, 255, 0.7)' },
  manageSpellsBtn: { backgroundColor: '#00bfff', padding: 18, borderRadius: 15, alignItems: 'center', marginTop: 10 },
  manageSpellsBtnText: { color: '#02112b', fontWeight: 'bold', fontSize: 14 },

  kitSelectionHeader: { marginBottom: 25 },
  kitSelectBtn: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: 'rgba(0, 191, 255, 0.1)', padding: 15, borderRadius: 12, borderWidth: 1, borderColor: '#00bfff' },
  kitSelectBtnText: { color: '#00bfff', fontWeight: 'bold', fontSize: 14 },
  kitCard: { backgroundColor: 'rgba(255, 255, 255, 0.05)', padding: 15, borderRadius: 12, marginBottom: 10, borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.1)' },
  kitCardTitle: { color: '#fff', fontSize: 16, fontWeight: 'bold', marginBottom: 5 },
  kitCardItems: { color: 'rgba(255, 255, 255, 0.6)', fontSize: 12, lineHeight: 18 },
  customKitBadge: { position: 'absolute', top: 15, right: 15, color: '#00fa9a', fontSize: 10, fontWeight: 'bold', backgroundColor: 'rgba(0,250,154,0.1)', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 5 },

  customAlertBox: { backgroundColor: '#102b56', width: '90%', borderRadius: 20, padding: 25, borderWidth: 1, borderColor: 'rgba(0,191,255,0.3)', alignItems: 'center' },
  customAlertTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold', marginBottom: 15, textAlign: 'center' },
  customAlertMessage: { color: 'rgba(255,255,255,0.8)', fontSize: 14, textAlign: 'center', lineHeight: 22, marginBottom: 25 },
  customAlertBtnRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, width: '100%', justifyContent: 'center' },
  customAlertBtn: { paddingVertical: 12, paddingHorizontal: 20, borderRadius: 10, alignItems: 'center', minWidth: '30%', borderWidth: 1 },
  customAlertBtnText: { fontWeight: 'bold', fontSize: 14 },
});

export const advancedStyles = StyleSheet.create({
  container: { flex: 1 },
  topBar: { paddingTop: 50, paddingBottom: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, backgroundColor: 'rgba(0,0,0,0.3)' },
  topBarTitle: { color: '#00fa9a', fontSize: 16, fontWeight: 'bold' },
  tabsContainer: { paddingVertical: 15, paddingHorizontal: 15, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.05)' },
  tabBtn: { paddingVertical: 8, paddingHorizontal: 20, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.05)' },
  tabBtnActive: { backgroundColor: '#00bfff' },
  tabBtnText: { color: 'rgba(255,255,255,0.5)', fontWeight: 'bold' },
  tabBtnTextActive: { color: '#02112b' },
  scrollContent: { padding: 20 },
  cardBlock: { backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 20, padding: 20, marginBottom: 20 },
  formGroup: { marginBottom: 20 },
  row: { flexDirection: 'row', justifyContent: 'space-between' },
  label: { fontSize: 11, fontWeight: 'bold', color: '#00bfff', marginBottom: 8, letterSpacing: 1 },
  input: { backgroundColor: 'rgba(0, 0, 0, 0.3)', borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.1)', borderRadius: 12, paddingHorizontal: 15, paddingVertical: 12, fontSize: 16, color: '#ffffff' },
  sectionTitle: { fontSize: 12, fontWeight: 'bold', color: '#fff', marginBottom: 15, marginTop: 10 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 10 },
  statBox: { width: '30%', backgroundColor: 'rgba(0, 0, 0, 0.3)', borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.1)', borderRadius: 12, padding: 10, alignItems: 'center' },
  statLabel: { fontSize: 14, fontWeight: 'bold', color: 'rgba(255, 255, 255, 0.5)', marginBottom: 5 },
  statInput: { fontSize: 24, fontWeight: 'bold', color: '#ffffff', textAlign: 'center' },
  toggleGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  toggleBtn: { paddingVertical: 10, paddingHorizontal: 15, borderRadius: 12, backgroundColor: 'rgba(0,0,0,0.3)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', alignItems: 'center', justifyContent: 'center' },
  toggleBtnActive: { backgroundColor: 'rgba(0,191,255,0.2)', borderColor: '#00bfff' },
  toggleBtnText: { color: 'rgba(255,255,255,0.6)', fontSize: 13, fontWeight: 'bold', textAlign: 'center' },
  toggleBtnTextActive: { color: '#00bfff' },
  limitBtn: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', alignItems: 'center', justifyContent: 'center' },
  limitBtnActive: { backgroundColor: 'rgba(0,250,154,0.1)', borderColor: '#00fa9a' },
  limitBtnText: { color: 'rgba(255,255,255,0.5)', fontSize: 11, fontWeight: 'bold', textAlign: 'center' },
  limitBtnTextActive: { color: '#00fa9a' },
  effectBuilder: { backgroundColor: 'rgba(0,0,0,0.2)', padding: 15, borderRadius: 12, marginBottom: 15, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  addEffectBtn: { backgroundColor: 'rgba(0, 191, 255, 0.1)', borderWidth: 1, borderColor: '#00bfff', padding: 12, borderRadius: 8, alignItems: 'center' },
  addEffectBtnText: { color: '#00bfff', fontWeight: 'bold', fontSize: 12 },
  effectRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: 'rgba(0, 191, 255, 0.1)', padding: 15, borderRadius: 12, marginBottom: 8, borderWidth: 1, borderColor: 'rgba(0,191,255,0.3)' },
  effectText: { color: '#fff', fontSize: 14, fontWeight: 'bold' },
  saveBtn: { backgroundColor: '#00fa9a', padding: 18, borderRadius: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 },
  saveBtnText: { color: '#02112b', fontSize: 16, fontWeight: 'bold', letterSpacing: 1 },
  acervoTabs: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 15, justifyContent: 'center' },
  acervoTabBtn: { paddingVertical: 8, paddingHorizontal: 12, backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 8 },
  acervoTabBtnActive: { backgroundColor: 'rgba(0,250,154,0.2)', borderWidth: 1, borderColor: '#00fa9a' },
  acervoTabBtnText: { color: 'rgba(255,255,255,0.5)', fontSize: 12, fontWeight: 'bold' },
  acervoTabBtnTextActive: { color: '#00fa9a' },
  acervoActions: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20, gap: 10 },
  acervoActionBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, backgroundColor: 'rgba(0,191,255,0.1)', paddingVertical: 12, borderRadius: 10, borderWidth: 1, borderColor: 'rgba(0,191,255,0.3)' },
  acervoActionText: { fontSize: 12, fontWeight: 'bold' },
  acervoItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.05)', padding: 15, borderRadius: 12, marginBottom: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  acervoItemActive: { borderColor: '#00fa9a', backgroundColor: 'rgba(0,250,154,0.05)' },
  acervoItemTitle: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  acervoItemSub: { color: 'rgba(255,255,255,0.5)', fontSize: 11, marginTop: 4, textTransform: 'uppercase', fontWeight: 'bold' },
  acervoDeleteBtn: { padding: 10, backgroundColor: 'rgba(255,100,100,0.1)', borderRadius: 8, marginLeft: 10 },
  checkbox: { width: 22, height: 22, borderRadius: 6, borderWidth: 2, borderColor: 'rgba(255,255,255,0.3)', marginRight: 15, alignItems: 'center', justifyContent: 'center' },
  checkboxActive: { backgroundColor: '#00fa9a', borderColor: '#00fa9a' },
  emptyText: { color: 'rgba(255,255,255,0.4)', textAlign: 'center', marginTop: 40, fontSize: 14 },
  modalOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0, 0, 0, 0.8)' },
  modalContent: { backgroundColor: '#102b56', borderRadius: 24, padding: 20, alignItems: 'center', width: '90%' },
  modalTitle: { fontSize: 18, fontWeight: 'bold', color: '#ffffff', marginBottom: 15 },
  searchInput: { backgroundColor: 'rgba(0,0,0,0.3)', color: '#fff', padding: 15, borderRadius: 12, marginBottom: 15, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', width: '100%' },
  modalCloseButton: { marginTop: 20, paddingVertical: 15, width: '100%', alignItems: 'center', backgroundColor: 'rgba(255, 255, 255, 0.05)', borderRadius: 12 },
  modalCloseText: { color: '#00bfff', fontWeight: 'bold' },
  catalogItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.05)' },
  catalogItemName: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  catalogItemSub: { color: 'rgba(0,191,255,0.5)', fontSize: 12, marginTop: 2 },
  radioCircle: { width: 36, height: 36, borderRadius: 18, borderWidth: 1, borderColor: 'rgba(255,255,255,0.3)', alignItems: 'center', justifyContent: 'center' },
  radioCircleSelected: { backgroundColor: 'rgba(0,191,255,0.2)', borderColor: '#00bfff' },
  featureBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(0,250,154,0.1)', borderWidth: 1, borderColor: '#00fa9a', borderRadius: 8, paddingLeft: 10, paddingRight: 5, paddingVertical: 4 },
  featureBadgeText: { color: '#00fa9a', fontSize: 11, fontWeight: 'bold', marginRight: 5 },
  featureBadgeInput: { backgroundColor: 'rgba(0,0,0,0.3)', color: '#fff', fontSize: 11, width: 35, height: 35, textAlign: 'center', borderRadius: 4, marginRight: 5 },
  hpHint: { color: 'rgba(255,255,255,0.5)', fontSize: 12, textAlign: 'center', marginTop: 15, lineHeight: 18 },
  counterText: { fontSize: 12, fontWeight: 'bold', color: '#00bfff', backgroundColor: 'rgba(0, 191, 255, 0.1)', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8 }
});

export const homeStyles = StyleSheet.create({
  container: { flex: 1 },
  buttonIconGap: { marginRight: 10 },
  header: { paddingTop: 60, paddingHorizontal: 20, paddingBottom: 20 },
  headerTitle: { fontSize: 28, fontWeight: 'bold', color: '#ffffff', letterSpacing: 1 },
  
  listContent: { paddingHorizontal: 20, paddingBottom: 180 },
  
  emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 40, marginTop: -50 },
  emptyIcon: { fontSize: 60, marginBottom: 20, opacity: 0.8 },
  emptyTitle: { fontSize: 20, fontWeight: 'bold', color: '#ffffff', marginBottom: 10 },
  emptyText: { fontSize: 14, color: 'rgba(255, 255, 255, 0.6)', textAlign: 'center', lineHeight: 22 },
  
  footer: { position: 'absolute', bottom: 20, left: 20, right: 20 },
  
  advancedButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(0, 191, 255, 0.1)', borderWidth: 1, borderColor: '#00bfff', borderRadius: 16, paddingVertical: 14, marginBottom: 15 },
  advancedButtonText: { fontSize: 14, fontWeight: 'bold', color: '#00bfff', letterSpacing: 1 },
  lanButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(0, 250, 154, 0.1)', borderWidth: 1, borderColor: '#00fa9a', borderRadius: 16, paddingVertical: 14, marginBottom: 15 },
  lanButtonText: { fontSize: 14, fontWeight: 'bold', color: '#00fa9a', letterSpacing: 1 },
  
  createButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#102b56', borderWidth: 1, borderColor: '#00bfff', borderRadius: 16, paddingVertical: 16, shadowColor: '#00bfff', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.4, shadowRadius: 5, elevation: 5 },
  createButtonIcon: { fontSize: 24, color: '#00bfff', marginRight: 10, fontWeight: '300' },
  createButtonText: { fontSize: 16, fontWeight: 'bold', color: '#ffffff', letterSpacing: 1 },

  versionContainer: {
    marginTop: 15,
    alignItems: 'center',
    opacity: 0.4,
  },
  versionText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: 'bold',
    letterSpacing: 2,
    textTransform: 'uppercase'
  }
});

export const lanSessionStyles = StyleSheet.create({
  container: { flex: 1 },
  topBar: { paddingTop: 55, paddingBottom: 12, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: 'rgba(0,0,0,0.25)' },
  topBarCenter: { alignItems: 'center' },
  topBarTitle: { color: appColors.textPrimary, fontSize: 18, fontWeight: 'bold' },
  topBarSub: { color: appColors.primary, fontSize: 11, fontWeight: 'bold', marginTop: 3 },
  topBarSpacer: { width: 28 },
  scrollContent: { padding: 20, paddingBottom: 80 },
  scrollContentFill: { flex: 1, padding: 20, paddingBottom: 80 },
  card: { backgroundColor: appColors.backgroundCard, borderRadius: 16, padding: 18, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', marginBottom: 16 },
  sectionTitle: { color: appColors.primary, fontSize: 15, fontWeight: 'bold', textTransform: 'uppercase', marginBottom: 14 },
  label: { color: 'rgba(255,255,255,0.65)', fontSize: 11, fontWeight: 'bold', marginBottom: 7, marginTop: 12, letterSpacing: 1 },
  input: { color: appColors.textPrimary, backgroundColor: 'rgba(0,0,0,0.25)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, fontSize: 16 },
  ruleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16, marginTop: 18, marginBottom: 18 },
  ruleTextBox: { flex: 1 },
  ruleTitle: { color: appColors.textPrimary, fontSize: 14, fontWeight: 'bold', marginBottom: 4 },
  ruleDescription: { color: 'rgba(255,255,255,0.55)', fontSize: 12, lineHeight: 18 },
  primaryButton: { backgroundColor: appColors.primary, borderRadius: 14, alignItems: 'center', paddingVertical: 15, marginTop: 8 },
  primaryButtonText: { color: appColors.primaryDark, fontSize: 14, fontWeight: 'bold' },
  joinSessionButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: appColors.successSoft, borderWidth: 1, borderColor: 'rgba(0,250,154,0.35)', borderRadius: 14, paddingVertical: 14, marginTop: 10 },
  joinSessionButtonText: { color: appColors.success, fontSize: 13, fontWeight: 'bold' },
  secondaryButton: { backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', borderRadius: 14, alignItems: 'center', paddingVertical: 14, marginTop: 16 },
  secondaryButtonText: { color: appColors.danger, fontSize: 13, fontWeight: 'bold' },
  hint: { color: 'rgba(255,255,255,0.62)', fontSize: 13, lineHeight: 20, textAlign: 'center', marginBottom: 16 },
  warningText: { color: appColors.warning, fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 12 },
  linkBox: { backgroundColor: 'rgba(0,0,0,0.3)', borderRadius: 10, padding: 10, marginTop: 12 },
  linkText: { color: 'rgba(255,255,255,0.65)', fontSize: 10, lineHeight: 16 },
  playerRow: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.07)' },
  playerName: { color: appColors.textPrimary, fontSize: 15, fontWeight: 'bold' },
  playerMeta: { color: appColors.primary, fontSize: 11, marginTop: 3 },
  characterRow: { backgroundColor: 'rgba(0,0,0,0.25)', borderRadius: 12, padding: 14, marginBottom: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  characterName: { color: appColors.textPrimary, fontSize: 16, fontWeight: 'bold' },
  characterDetails: { color: 'rgba(255,255,255,0.55)', fontSize: 12, marginTop: 4 },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  rowWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  mutedText: { color: appColors.textMuted, fontSize: 12, lineHeight: 18 },
  strongText: { color: appColors.textPrimary, fontSize: 14, fontWeight: 'bold' },
  statusPill: { alignSelf: 'flex-start', borderRadius: 999, borderWidth: 1, borderColor: 'rgba(0,191,255,0.35)', backgroundColor: appColors.primarySoft, paddingHorizontal: 10, paddingVertical: 5 },
  statusPillPaused: { borderColor: 'rgba(255,215,0,0.45)', backgroundColor: appColors.warningSoft },
  statusPillText: { color: appColors.primary, fontSize: 11, fontWeight: 'bold', textTransform: 'uppercase' },
  statusPillTextPaused: { color: appColors.warning },
  sessionEventRow: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: 'rgba(0,0,0,0.2)', borderRadius: 10, padding: 10, marginBottom: 8 },
  sessionEventText: { color: appColors.textPrimary, fontSize: 12, lineHeight: 18, flex: 1 },
  smallButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: 'rgba(255,255,255,0.06)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', borderRadius: 10, paddingHorizontal: 11, paddingVertical: 9 },
  smallButtonActive: { backgroundColor: appColors.primarySoft, borderColor: appColors.primary },
  smallButtonDanger: { backgroundColor: appColors.dangerSoft, borderColor: 'rgba(255,102,102,0.35)' },
  smallButtonSuccess: { backgroundColor: appColors.successSoft, borderColor: 'rgba(0,250,154,0.35)' },
  smallButtonText: { color: appColors.textPrimary, fontSize: 11, fontWeight: 'bold' },
  smallButtonTextActive: { color: appColors.primary },
  smallButtonTextDanger: { color: appColors.danger },
  smallButtonTextSuccess: { color: appColors.success },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  metricBox: { minWidth: '30%', flexGrow: 1, backgroundColor: 'rgba(0,0,0,0.22)', borderRadius: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', padding: 10 },
  metricLabel: { color: appColors.textMuted, fontSize: 10, fontWeight: 'bold', textTransform: 'uppercase', marginBottom: 3 },
  metricValue: { color: appColors.textPrimary, fontSize: 18, fontWeight: 'bold' },
  toolbar: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  savedSessionRow: { backgroundColor: 'rgba(0,0,0,0.22)', borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', padding: 12, marginTop: 10 },
  savedSessionContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  savedSessionTextBox: { flex: 1, minWidth: 0 },
  savedSessionActions: { flexDirection: 'row', gap: 8, flexShrink: 0 },
  savedSessionTitle: { color: appColors.textPrimary, fontSize: 14, fontWeight: 'bold' },
  savedSessionMeta: { color: appColors.textMuted, fontSize: 11, marginTop: 4 },
  catalogSummaryBox: { backgroundColor: 'rgba(0,0,0,0.2)', borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', padding: 12, marginTop: 14 },
  catalogSummaryRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, flexWrap: 'wrap' },
  catalogSummaryTextBox: { flex: 1, minWidth: 180 },
  catalogSummaryText: { color: appColors.textPrimary, fontSize: 13, fontWeight: 'bold' },
  qrHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, marginBottom: 10 },
  qrHeaderTextBox: { flex: 1 },
  qrIconBox: { width: 38, height: 38, borderRadius: 19, backgroundColor: appColors.primarySoft, borderWidth: 1, borderColor: 'rgba(0,191,255,0.35)', alignItems: 'center', justifyContent: 'center', marginTop: 1 },
  scannerBox: { height: 280, borderRadius: 14, overflow: 'hidden', borderWidth: 1, borderColor: 'rgba(0,191,255,0.35)', backgroundColor: appColors.backgroundDeep },
  scannerCamera: { flex: 1 },
  scannerFrame: { position: 'absolute', left: '14%', right: '14%', top: '18%', bottom: '18%', borderWidth: 2, borderColor: appColors.primary, borderRadius: 12 },
  modalOverlay: { flex: 1, backgroundColor: appColors.overlayStrong, justifyContent: 'flex-end' },
  modalPanel: { maxHeight: '88%', backgroundColor: appColors.backgroundDeep, borderTopLeftRadius: 18, borderTopRightRadius: 18, borderWidth: 1, borderColor: 'rgba(0,191,255,0.35)', padding: 18 },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginBottom: 12 },
  modalTitle: { color: appColors.textPrimary, fontSize: 18, fontWeight: 'bold' },
  modalCloseButton: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.08)' },
  searchInput: { color: appColors.textPrimary, backgroundColor: 'rgba(0,0,0,0.28)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', borderRadius: 12, paddingHorizontal: 14, paddingVertical: 11, fontSize: 14, marginBottom: 12 },
  filterRail: { flexDirection: 'row', gap: 8, paddingBottom: 12 },
  filterChip: { borderRadius: 999, borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)', paddingHorizontal: 12, paddingVertical: 7, backgroundColor: 'rgba(255,255,255,0.04)' },
  filterChipActive: { borderColor: appColors.primary, backgroundColor: appColors.primarySoft },
  filterChipText: { color: appColors.textMuted, fontSize: 11, fontWeight: 'bold' },
  filterChipTextActive: { color: appColors.primary },
  catalogRow: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: 'rgba(255,255,255,0.04)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', borderRadius: 12, padding: 12, marginBottom: 8 },
  catalogRowActive: { borderColor: appColors.primary, backgroundColor: appColors.primarySoft },
  catalogCheck: { width: 24, height: 24, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.25)', alignItems: 'center', justifyContent: 'center' },
  catalogCheckActive: { backgroundColor: appColors.primary, borderColor: appColors.primary },
  catalogTextBox: { flex: 1 },
  catalogName: { color: appColors.textPrimary, fontSize: 14, fontWeight: 'bold' },
  catalogMeta: { color: appColors.textMuted, fontSize: 11, marginTop: 3 },
  catalogTag: { color: appColors.primary, fontSize: 10, fontWeight: 'bold', textTransform: 'uppercase' },
  playerCard: { backgroundColor: 'rgba(0,0,0,0.22)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', borderRadius: 14, padding: 14, marginBottom: 12 },
  playerCardActive: { borderColor: appColors.primary, backgroundColor: appColors.primarySoft },
  playerHeader: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, alignItems: 'flex-start', marginBottom: 10 },
  playerTitleBox: { flex: 1 },
  hpTrack: { height: 8, backgroundColor: appColors.dangerSoft, borderRadius: 999, overflow: 'hidden', marginTop: 8 },
  hpFill: { height: '100%', backgroundColor: appColors.danger, borderRadius: 999 },
  statGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 10 },
  statPill: { minWidth: '30%', flexGrow: 1, backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 8, paddingVertical: 7, paddingHorizontal: 8, alignItems: 'center' },
  statLabel: { color: appColors.textMuted, fontSize: 9, fontWeight: 'bold' },
  statValue: { color: appColors.textPrimary, fontSize: 14, fontWeight: 'bold', marginTop: 2 },
  inventoryBox: { backgroundColor: 'rgba(0,0,0,0.2)', borderRadius: 10, padding: 10, marginTop: 10 },
  inventoryText: { color: appColors.textMuted, fontSize: 12, lineHeight: 18 },
  effectBox: { backgroundColor: 'rgba(0,250,154,0.08)', borderWidth: 1, borderColor: 'rgba(0,250,154,0.22)', borderRadius: 10, padding: 10, marginTop: 10 },
  effectRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginTop: 6 },
  effectText: { color: appColors.success, fontSize: 12, fontWeight: 'bold', flex: 1 },
  effectForm: { backgroundColor: 'rgba(0,0,0,0.22)', borderRadius: 14, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', padding: 14, marginTop: 12 },
  effectInputRow: { flexDirection: 'row', gap: 8 },
  effectInput: { flex: 1, color: appColors.textPrimary, backgroundColor: 'rgba(0,0,0,0.26)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, fontSize: 14, marginTop: 8 },
  fullWidthButton: { width: '100%', marginTop: 10 },
});

export const spellSelectorStyles = StyleSheet.create({
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'flex-end' },
  modalOverlayCenter: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalContentFullScreen: { backgroundColor: '#02112b', borderTopLeftRadius: 30, borderTopRightRadius: 30, padding: 15, height: '90%', marginBottom: 10, borderBottomLeftRadius: 30, borderBottomRightRadius: 30, borderWidth: 1, borderColor: '#00bfff' },
  
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 10 },
  modalTitle: { color: '#fff', fontSize: 20, fontWeight: 'bold' },
  counterText: { color: '#00fa9a', fontSize: 13, fontWeight: 'bold', marginTop: 4 },
  closeBtn: { padding: 5, backgroundColor: 'rgba(255,255,255,0.1)', borderRadius: 10 },
  hpHint: { color: 'rgba(255,255,255,0.5)', fontSize: 11, marginBottom: 15 },
  
  searchBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 12, paddingHorizontal: 15, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', marginBottom: 15 },
  searchIcon: { marginRight: 10 },
  searchInput: { flex: 1, color: '#fff', paddingVertical: 12, fontSize: 15 },

  filterTitle: { color: '#00bfff', fontSize: 10, fontWeight: 'bold', textTransform: 'uppercase', marginBottom: 5, marginLeft: 2 },
  filterPill: { paddingVertical: 6, paddingHorizontal: 12, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  filterPillActive: { backgroundColor: 'rgba(0,191,255,0.2)', borderColor: '#00bfff' },
  filterPillText: { color: 'rgba(255,255,255,0.5)', fontSize: 11, fontWeight: 'bold' },
  filterPillTextActive: { color: '#00bfff' },

  spellCard: { backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 16, padding: 15, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', marginBottom: 12 },
  spellCardActive: { backgroundColor: '#00bfff', borderColor: '#00bfff' },
  spellCardLocked: { borderColor: '#00fa9a', backgroundColor: 'rgba(0,250,154,0.05)' },
  
  spellCardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  spellCardTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  
  tag: { backgroundColor: 'rgba(0,0,0,0.4)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  tagText: { color: '#00bfff', fontSize: 9, fontWeight: 'bold' },
  tagDark: { backgroundColor: 'rgba(0,0,0,0.2)' },
  tagTextDark: { color: '#02112b' },

  spellCardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 15, paddingTop: 12, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.1)' },
  spellCardEffect: { color: '#00fa9a', fontSize: 12, fontWeight: 'bold', flex: 1 },
  infoBtn: { padding: 4 },

  emptyText: { color: 'rgba(255,255,255,0.3)', textAlign: 'center', marginTop: 40, fontSize: 14 },

  spellDetailCard: { backgroundColor: '#102b56', borderRadius: 24, padding: 25, width: '100%', borderWidth: 1, borderColor: '#00bfff' },
  spellDetailName: { color: '#fff', fontSize: 22, fontWeight: 'bold', marginBottom: 5 },
  spellDetailLevel: { color: '#00bfff', fontSize: 12, fontWeight: 'bold', textTransform: 'uppercase', marginBottom: 15 },
  divider: { height: 1, backgroundColor: 'rgba(255,255,255,0.1)', marginBottom: 15 },
  spellDetailInfoGrid: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, backgroundColor: 'rgba(0,0,0,0.2)', padding: 12, borderRadius: 12 },
  spellDetailInfoItem: { alignItems: 'center', flex: 1 },
  spellDetailInfoLabel: { color: 'rgba(255,255,255,0.4)', fontSize: 9, fontWeight: 'bold', letterSpacing: 1, marginBottom: 4 },
  spellDetailInfoValue: { color: '#fff', fontSize: 13, fontWeight: 'bold', textAlign: 'center' },
  spellDetailDescription: { color: 'rgba(255,255,255,0.8)', fontSize: 14, lineHeight: 22 },
  modalCloseButton: { marginTop: 20, paddingVertical: 15, width: '100%', alignItems: 'center', backgroundColor: 'rgba(255, 255, 255, 0.05)', borderRadius: 12 },
  modalCloseText: { color: '#00bfff', fontWeight: 'bold' }
});

export const characterCardStyles = StyleSheet.create({
  characterCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 16,
    padding: 15,
    marginBottom: 15,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  cardInfo: {
    flex: 1,
    marginLeft: 15,
    marginRight: 10,
  },
  characterName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 4,
  },
  characterDetails: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.6)',
  },
  sessionDetails: {
    fontSize: 12,
    color: '#00fa9a',
    marginTop: 4,
    fontWeight: '600',
  },
  levelBadge: {
    backgroundColor: 'rgba(0, 191, 255, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(0, 191, 255, 0.3)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  levelText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#00bfff',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    maxWidth: 340,
    backgroundColor: '#0a1930',
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: 'rgba(0, 191, 255, 0.3)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'center',
  },
  modalSubtitle: {
    fontSize: 16,
    color: '#00bfff',
    textAlign: 'center',
    marginBottom: 20,
    fontWeight: '600',
  },
  modalWarningText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 25,
    lineHeight: 22,
  },
  optionButton: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
    alignItems: 'center',
  },
  optionButtonNoBorder: {
    borderBottomWidth: 0,
  },
  optionText: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '600',
  },
  deleteText: {
    fontSize: 16,
    color: '#ff6666',
    fontWeight: '600',
  },
  confirmDeleteButton: {
    backgroundColor: 'rgba(255, 50, 50, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(255, 50, 50, 0.4)',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 10,
  },
  confirmDeleteText: {
    color: '#ff6666',
    fontWeight: 'bold',
    fontSize: 16,
  },
  cancelButton: {
    marginTop: 15,
    paddingVertical: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    alignItems: 'center',
  },
  cancelText: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.8)',
    fontWeight: 'bold',
  },
});

export const diceRollerStyles = StyleSheet.create({
  canvasContainer: { ...StyleSheet.absoluteFillObject, zIndex: 9999, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center' },
  resultOverlay: { position: 'absolute', alignSelf: 'center', backgroundColor: 'rgba(0,0,0,0.9)', paddingHorizontal: 50, paddingVertical: 20, borderRadius: 25, borderWidth: 2, borderColor: '#00bfff', alignItems: 'center', elevation: 10 },
  totalText: { color: '#00fa9a', fontSize: 64, fontWeight: 'bold', textShadowColor: 'rgba(0, 250, 154, 0.5)', textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 10 },
  
  highLowContainer: { flexDirection: 'row', gap: 15, marginTop: 10, marginBottom: 5 },
  highLowBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, borderWidth: 1, alignItems: 'center', minWidth: 60 },
  highLowLabel: { fontSize: 9, fontWeight: 'bold', letterSpacing: 1, marginBottom: 2 },
  highLowValue: { fontSize: 20, fontWeight: 'bold' },

  tapToCloseText: { color: 'rgba(255,255,255,0.4)', fontSize: 12, marginTop: 15, textTransform: 'uppercase' },
  draggableContainer: { position: 'absolute', top: 0, left: 0, width: diceFabSize, height: diceFabSize, zIndex: 10000 },
  fab: { width: diceFabSize, height: diceFabSize, borderRadius: 30, backgroundColor: '#00bfff', justifyContent: 'center', alignItems: 'center', elevation: 8, borderWidth: 2, borderColor: '#102b56' },
  menuContainer: { position: 'absolute', width: 250 },
  qtySelector: { position: 'absolute', flexDirection: 'row', backgroundColor: 'rgba(16,43,86,0.9)', padding: 8, borderRadius: 30, gap: 5, borderWidth: 1, borderColor: '#00bfff' },
  qtyBtn: { width: 35, height: 35, borderRadius: 17.5, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.1)' },
  qtyBtnActive: { backgroundColor: '#00bfff' },
  qtyBtnText: { color: '#fff', fontWeight: 'bold' },
  qtyBtnTextActive: { color: '#102b56' },
  subButton: { position: 'absolute', width: 45, height: 45, borderRadius: 22.5, justifyContent: 'center', alignItems: 'center', elevation: 4, borderWidth: 2, borderColor: '#102b56' },
  subButtonText: { position: 'absolute', color: '#fff', backgroundColor: 'rgba(0,0,0,0.8)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4, fontWeight: 'bold', fontSize: 12 },
});

export const animatedIconStyles = StyleSheet.create({
  imageContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  glow: {
    width: 201,
    height: 201,
    position: 'absolute',
  },
  iconContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 128,
    height: 128,
    zIndex: 100,
  },
  image: {
    position: 'absolute',
    width: 76,
    height: 71,
  },
  background: {
    borderRadius: 40,
    experimental_backgroundImage: `linear-gradient(180deg, #3C9FFE, #0274DF)`,
    width: 128,
    height: 128,
    position: 'absolute',
  },
  backgroundSolidColor: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#208AEF',
    zIndex: 1000,
  },
});

export const animatedIconWebStyles = StyleSheet.create({
  container: {
    alignItems: 'center',
    width: '100%',
    zIndex: 1000,
    position: 'absolute',
    top: 128 / 2 + 138,
  },
  imageContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  glow: {
    width: 201,
    height: 201,
    position: 'absolute',
  },
  iconContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 128,
    height: 128,
  },
  image: {
    position: 'absolute',
    width: 76,
    height: 71,
  },
  background: {
    width: 128,
    height: 128,
    position: 'absolute',
  },
  expoLogoBackground: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 40,
    experimental_backgroundImage: `linear-gradient(180deg, #3C9FFE, #0274DF)`,
  },
});

export const appTabsWebStyles = StyleSheet.create({
  tabListContainer: {
    position: 'absolute',
    width: '100%',
    padding: Spacing.three,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  innerContainer: {
    paddingVertical: Spacing.two,
    paddingHorizontal: Spacing.five,
    borderRadius: Spacing.five,
    flexDirection: 'row',
    alignItems: 'center',
    flexGrow: 1,
    gap: Spacing.two,
    maxWidth: MaxContentWidth,
  },
  brandText: {
    marginRight: 'auto',
  },
  pressed: {
    opacity: 0.7,
  },
  tabButtonView: {
    paddingVertical: Spacing.one,
    paddingHorizontal: Spacing.three,
    borderRadius: Spacing.three,
  },
  externalPressable: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: Spacing.one,
    marginLeft: Spacing.three,
  },
});

export const hintRowStyles = StyleSheet.create({
  stepRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  codeSnippet: {
    borderRadius: Spacing.two,
    paddingVertical: Spacing.half,
    paddingHorizontal: Spacing.two,
  },
});

export const themedTextStyles = StyleSheet.create({
  small: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: 500,
  },
  smallBold: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: 700,
  },
  default: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: 500,
  },
  title: {
    fontSize: 48,
    fontWeight: 600,
    lineHeight: 52,
  },
  subtitle: {
    fontSize: 32,
    lineHeight: 44,
    fontWeight: 600,
  },
  link: {
    lineHeight: 30,
    fontSize: 14,
  },
  linkPrimary: {
    lineHeight: 30,
    fontSize: 14,
    color: '#3c87f7',
  },
  code: {
    fontFamily: Fonts.mono,
    fontWeight: Platform.select({ android: 700 }) ?? 500,
    fontSize: 12,
  },
});

export const webBadgeStyles = StyleSheet.create({
  container: {
    padding: Spacing.five,
    alignItems: 'center',
    gap: Spacing.two,
  },
  versionText: {
    textAlign: 'center',
  },
  badgeImage: {
    width: 123,
    aspectRatio: 123 / 24,
  },
});

export const collapsibleStyles = StyleSheet.create({
  heading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
  },
  pressedHeading: {
    opacity: 0.7,
  },
  button: {
    width: Spacing.four,
    height: Spacing.four,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: {
    marginTop: Spacing.three,
    borderRadius: Spacing.three,
    marginLeft: Spacing.four,
    padding: Spacing.four,
  },
});
